### ISSUE TITLE
discord server

### ISSUE THREAD

**Issue by Twinkle0820** [hafyzwithawhy/Colorant#3]
the server deleted?

**Comment by hafyzwithawhy** [comment]
yes, sadly... i will create a new discord server and account today 😛 they cant stop me

**Comment by jerenjoy** [comment]
Waiting brother

**Comment by hafyzwithawhy** [comment]
https://discord.gg/fKyySY3nSw

**Comment by Loisldf** [comment]
Invalid

**Comment by jerenjoy** [comment]
New link please, it says invalid or expired

**Comment by hafyzwithawhy** [comment]
https://discord.gg/P92kGvubRd
